# *******************************
# CREATE NEW REPORT
# POST /reports
# *******************************
### 🟢 VALID
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Lamborghini",
  "model": "Urus",
  "year": 2023,
  "mileage": 27,
  "lng": 43.8352078,
  "lat": -79.8013401,
  "price": 419000
}

### 🟢 VALID
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Jaguar",
  "model": "F-Type",
  "year": 2021,
  "mileage": 119,
  "lng": 43.8352078,
  "lat": -79.8013401,
  "price": 125300
}

### 🚫 INVALID
POST http://localhost:3000/reports
Content-Type: application/json

{
}

# *******************************
# APPROVE | DISAPPROVE REPORT
# PATCH /reports/:id
# *******************************
### 🟢 VALID
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": true
}


### 🟢 VALID
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": false
}


# *******************************
# GET ESTIMATE
# GET /reports
# Using Query Strings
# *******************************
### 🟢 VALID
GET http://localhost:3000/reports?make=Jaguar&model=F-Type&lng=43.75&lat=-79.99&mileage=2000&year=2022