# *******************************
# FETCH ALL USERS
# GET /auth/signup
# *******************************
### 🟢 VALID
GET http://localhost:3000/auth/signup


# *******************************
# SIGNUP
# POST /auth/signup
# *******************************

### 🟢 VALID
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "demo@demo.com",
  "password": "123456"
}

### 🚫 INVALID
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "password": "123456"
}

### 🚫 INVALID
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "t@t.com"
}

### 🚫 INVALID
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
}

# *******************************
# SIGNIN
# POST /auth/signin
# *******************************

### 🟢 VALID
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "demo@demo.com",
  "password": "123456"
}

### 🚫 INVALID
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "password": "123456"
}

### 🚫 INVALID
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "demo@demo.com"
}

### 🚫 INVALID
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
}

# *******************************
# SIGN OUT
# GET /auth/signout
# *******************************
### 🟢 VALID
POST http://localhost:3000/auth/signout

# *******************************
# CURRENT USER
# GET /auth/whoami
# *******************************
### 🟢 VALID
GET http://localhost:3000/auth/whoami

# *******************************
# FETCH USER BY id
# GET /auth/:id
# *******************************
### 🟢 VALID
GET http://localhost:3000/auth/5


### 🚫 INVALID
GET http://localhost:3000/auth/500


# *******************************
# FETCH USER BY email
# GET /auth
# *******************************
### 🟢 VALID
GET http://localhost:3000/auth?email=t2@t.com


### 🚫 INVALID
GET http://localhost:3000/auth?email=not@found.com

# *******************************
# UPDATE USER BY id
# PATCH /auth/signup/:id
# *******************************
### 🟢 VALID
PATCH http://localhost:3000/auth/5
Content-Type: application/json

{
  "email": "updated11223344@updated.com"
}

### 🟢 VALID
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "password": "newpasword"
}

### 🚫 INVALID
PATCH http://localhost:3000/auth/500
Content-Type: application/json

{
}

# *******************************
# DELETE USER BY id
# DELETE /auth/signup/:id
# *******************************
### 🟢 VALID
DELETE http://localhost:3000/auth/1

### 🚫 INVALID
DELETE http://localhost:3000/auth/500
